### ISSUE TITLE
What's the purpose of the metadata service?

### ISSUE THREAD

**Issue by onitake** [Ultimaker/libCharon#45]
libCharon contains a "metadata service" that listens for DBus messages, but nothing explains what the purpose of this service is.
The documentation just says "TODO": https://github.com/Ultimaker/libCharon/blob/master/s-line/docs/service.md

Also, there is a `WantedBy` on a `griffin.target`, which isn't explained anywhere either: https://github.com/Ultimaker/libCharon/blob/master/s-line/service/charon.service#L16

Can you elaborate why this service is needed, what will happen when it's not running, and why it should be installed system-wide?

**Comment by robinmdh** [comment]
This package is made to be installed on an ultimaker printer.
The Service was made to communicate with the display software in the printer. The thumbnails are used when a user scrolls trough files on a USB stick. The metadata is also used in the preview when the user clicks on a file to show the time/material, etc it will take to print, etc.
On the printer, if this is not running it means that printing from USB no longer has any info on what you will be printing beyond the filename.
So for use in Cura this service **is not needed.**

It works well enough that this hasn't been touched which explains the extremely lacking documentation at least a little bit.

The main software on the printer is called griffin and the `griffin.target` is started which causes all the printer services to start.

I hope that answers this adequately?

**Comment by onitake** [comment]
Much obliged, @robinmdh !
I kind of suspected it would be something like this, but wondered if the metadata service also served a purpose in the Cura desktop version.
